import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import localFont from 'next/font/local';

import { cn } from '@/shared/lib/utils';
import { Dialog } from '@/shared/ui/components/atoms';
import { Footer, Header, Preloader } from '@/shared/ui/components/organisms';

import './globals.css';

const workSans = Work_Sans({
  variable: '--font-work-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const aeonik = localFont({
  src: [
    {
      path: '/fonts/aeonik/light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '/fonts/aeonik/regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/aeonik/medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '/fonts/aeonik/semi-bold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '/fonts/aeonik/bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(workSans.variable, aeonik.className, 'antialiased')}>
        <Header />
        {children}
        <Footer />
        <Dialog />
        <Preloader />
      </body>
    </html>
  );
}
